dist: trusty
sudo: true
language: node_js

node_js:
  - '7.7'

branches:
  only:
  - master

notifications:
  email: false

before_install:
 - export CHROME_BIN=/usr/bin/google-chrome
 - export DISPLAY=:99.0
 - sh -e /etc/init.d/xvfb start
 - sudo apt-get update
 - sudo apt-get install -y libappindicator1 fonts-liberation
 - wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
 - sudo dpkg -i google-chrome*.deb

before_script:
  - npm run lint
  - npm run e2e
  - npm test

script:
  - npm run coveralls
  - npm run build-prod

deploy:
    provider: firebase
    token:
        secure: "1/--L0AaSGQs2QmPp__nTt2L239vvJ5OvhjiRQk3aA8pc"
    on:
      branch: master

