dist: trusty
sudo: true
language: node_js

node_js:
  - '7.7'

branches:
  only:
  - master

notifications:
  email: false

cache:
  directories: node_modules

addons:
apt:
  sources:
    - google-chrome

before_install:
  - export CHROME_BIN=chromium-browser
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start

before_script:
  - npm install coveralls

script:
  - npm run lint
  - npm run build-prod
  - npm test --single-run --code-coverage

after_script:
  - cat ./coverage/coverage.lcov | ./node_modules/coveralls/bin/coveralls.js

deploy:
    provider: firebase
    token:
        secure: "1/--L0AaSGQs2QmPp__nTt2L239vvJ5OvhjiRQk3aA8pc"
    on:
      branch: master

